# Generated by Django 2.0.5 on 2020-03-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default=None, max_length=10, null=True)),
                ('email', models.EmailField(default=None, max_length=100, null=True)),
                ('is_phone_number_verified', models.BooleanField(default=False, verbose_name='Phone Number Verified')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
