# Generated by Django 2.0.5 on 2020-03-17 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clickpost', '0002_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.BigIntegerField()),
                ('sent_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clickpost.User')),
            ],
            options={
                'db_table': 'sms_notification',
            },
        ),
        migrations.CreateModel(
            name='WhtsappNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.BigIntegerField()),
                ('sent_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(max_length=100)),
                ('template_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clickpost.User')),
            ],
            options={
                'db_table': 'whtsapp_notification',
            },
        ),
    ]
