# Generated by Django 2.0.5 on 2020-03-17 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clickpost', '0003_smsnotification_whtsappnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusNotificationTypeRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('notification_type', models.PositiveIntegerField(choices=[(1, 'sms_notification'), (2, 'whatsapp_notification')])),
                ('is_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clickpost.User')),
            ],
            options={
                'db_table': 'status_notification_type_records',
            },
        ),
    ]
