# Generated by Django 2.0.5 on 2020-03-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickpost', '0004_statusnotificationtyperecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.EmailField(default=None, max_length=100),
        ),
    ]
