# Generated by Django 2.0.5 on 2020-03-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickpost', '0005_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
